console.log("Hello world!")
console.log(12)
console.log(1.9)
console.log(typeof 1)
console.log(typeof 2.0)
console.log(1 - 4)
console.log(typeof (3 / 4))
console.log(2 ** 3)
console.log(5 % 2)
console.log(9 / 3 | 0) 